#!/usr/bin/env python
""" generated source for module LFIdeModule """
# 
#  * generated by Xtext 2.23.0
#  
# package: org.lflang.ide
# 
#  * Use this class to register ide components.
#  
class LFIdeModule(AbstractLFIdeModule):
    """ generated source for class LFIdeModule """
