#!/usr/bin/env python
""" generated source for module LFUiModule """
# 
#  * generated by Xtext 2.23.0
#  
# package: org.lflang.ui
# import org.eclipse.ui.plugin.AbstractUIPlugin
# import org.eclipse.xtext.generator.IShouldGenerate
# import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator
# import org.eclipse.xtext.ui.wizard.IProjectCreator
# import org.eclipse.xtext.ui.wizard.template.DefaultTemplateProjectCreator

from org.lflang.ui.highlighting.LFSemanticHighlightingCalculator

# 
#  * Use this class to register components to be used within the Eclipse IDE.
#  
class LFUiModule(LFUiModuleImpl):
    """ generated source for class LFUiModule """
    def __init__(self, plugin):
        """ generated source for method __init__ """
        super(LFUiModule, self).__init__(plugin)

    #  The rebuild checker that considers markers by error reporter. 
    def bindIShouldGenerate(self):
        """ generated source for method bindIShouldGenerate """
        return EclipseBasedShouldGenerateLF.__class__

    #  Register LF specific highlighting provider 
    def bindISemanticHighlightingCalculator(self):
        """ generated source for method bindISemanticHighlightingCalculator """
        return LFSemanticHighlightingCalculator.__class__

    #      * Manually activate project template support.
    #      * This would be added by the TemplateProjectWizardFragment (in mwe file) to the AbstractLFUiModule 
    #      * but we do not want this fragment to create xtend files.
    #      
    @SuppressWarnings("restriction")
    def bindIProjectCreator(self):
        """ generated source for method bindIProjectCreator """
        return DefaultTemplateProjectCreator.__class__
