#!/usr/bin/env python
""" generated source for module BuiltinTriggerRefImpl """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf.impl
# import org.eclipse.emf.common.notify.Notification
# import org.eclipse.emf.ecore.EClass
# import org.eclipse.emf.ecore.impl.ENotificationImpl

from org.lflang.lf import BuiltinTrigger

from org.lflang.lf import BuiltinTriggerRef

from org.lflang.lf import LfPackage

# 
#  * <!-- begin-user-doc -->
#  * An implementation of the model object '<em><b>Builtin Trigger Ref</b></em>'.
#  * <!-- end-user-doc -->
#  * <p>
#  * The following features are implemented:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.impl.BuiltinTriggerRefImpl#getType <em>Type</em>}</li>
#  * </ul>
#  *
#  * @generated
#  
class BuiltinTriggerRefImpl(TriggerRefImpl, BuiltinTriggerRef):
    """ generated source for class BuiltinTriggerRefImpl """
    #    * The default value of the '{@link #getType() <em>Type</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #getType()
    #    * @generated
    #    * @ordered
    #    
    TYPE_EDEFAULT = BuiltinTrigger.STARTUP

    #    * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #getType()
    #    * @generated
    #    * @ordered
    #    
    type = TYPE_EDEFAULT

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __init__(self):
        """ generated source for method __init__ """
        super(BuiltinTriggerRefImpl, self).__init__()

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eStaticClass(self):
        """ generated source for method eStaticClass """
        return LfPackage.Literals.BUILTIN_TRIGGER_REF

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def getType(self):
        """ generated source for method getType """
        return self.type

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def setType(self, newType):
        """ generated source for method setType """
        oldType = self.type
        self.type = self.TYPE_EDEFAULT if newType == None else newType
        if eNotificationRequired():
            eNotify(ENotificationImpl(self, Notification.SET, LfPackage.BUILTIN_TRIGGER_REF__TYPE, oldType, self.type))

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eGet(self, featureID, resolve, coreType):
        """ generated source for method eGet """
        if featureID == LfPackage.BUILTIN_TRIGGER_REF__TYPE:
            return self.getType()
        return super(BuiltinTriggerRefImpl, self).eGet(featureID, resolve, coreType)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eSet(self, featureID, newValue):
        """ generated source for method eSet """
        if featureID == LfPackage.BUILTIN_TRIGGER_REF__TYPE:
            self.setType(newValue)
            return
        super(BuiltinTriggerRefImpl, self).eSet(featureID, newValue)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eUnset(self, featureID):
        """ generated source for method eUnset """
        if featureID == LfPackage.BUILTIN_TRIGGER_REF__TYPE:
            self.setType(self.TYPE_EDEFAULT)
            return
        super(BuiltinTriggerRefImpl, self).eUnset(featureID)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eIsSet(self, featureID):
        """ generated source for method eIsSet """
        if featureID == LfPackage.BUILTIN_TRIGGER_REF__TYPE:
            return self.type != self.TYPE_EDEFAULT
        return super(BuiltinTriggerRefImpl, self).eIsSet(featureID)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __str__(self):
        """ generated source for method toString """
        if eIsProxy():
            return super(BuiltinTriggerRefImpl, self).__str__()
        result = StringBuilder(super(BuiltinTriggerRefImpl, self).__str__())
        result.append(" (type: ")
        result.append(self.type)
        result.append(')')
        return result.__str__()

# BuiltinTriggerRefImpl
