#!/usr/bin/env python
""" generated source for module ExpressionImpl """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf.impl
# import org.eclipse.emf.ecore.EClass
# import org.eclipse.emf.ecore.impl.MinimalEObjectImpl

from org.lflang.lf import Expression

from org.lflang.lf import LfPackage

# 
#  * <!-- begin-user-doc -->
#  * An implementation of the model object '<em><b>Expression</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * @generated
#  
class ExpressionImpl(MinimalEObjectImpl, Container, Expression):
    """ generated source for class ExpressionImpl """
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __init__(self):
        """ generated source for method __init__ """
        super(ExpressionImpl, self).__init__()

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eStaticClass(self):
        """ generated source for method eStaticClass """
        return LfPackage.Literals.EXPRESSION

# ExpressionImpl
