#!/usr/bin/env python
""" generated source for module IPV6HostImpl """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf.impl
# import org.eclipse.emf.ecore.EClass

from org.lflang.lf import IPV6Host

from org.lflang.lf import LfPackage

# 
#  * <!-- begin-user-doc -->
#  * An implementation of the model object '<em><b>IPV6 Host</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * @generated
#  
class IPV6HostImpl(HostImpl, IPV6Host):
    """ generated source for class IPV6HostImpl """
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __init__(self):
        """ generated source for method __init__ """
        super(IPV6HostImpl, self).__init__()

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eStaticClass(self):
        """ generated source for method eStaticClass """
        return LfPackage.Literals.IPV6_HOST

# IPV6HostImpl
