#!/usr/bin/env python
""" generated source for module OutputImpl """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf.impl
# import org.eclipse.emf.ecore.EClass

from org.lflang.lf import LfPackage

from org.lflang.lf import Output

# 
#  * <!-- begin-user-doc -->
#  * An implementation of the model object '<em><b>Output</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * @generated
#  
class OutputImpl(PortImpl, Output):
    """ generated source for class OutputImpl """
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __init__(self):
        """ generated source for method __init__ """
        super(OutputImpl, self).__init__()

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eStaticClass(self):
        """ generated source for method eStaticClass """
        return LfPackage.Literals.OUTPUT

# OutputImpl
