#!/usr/bin/env python
""" generated source for module PreambleImpl """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf.impl
# import org.eclipse.emf.common.notify.Notification
# import org.eclipse.emf.common.notify.NotificationChain
# import org.eclipse.emf.ecore.EClass
# import org.eclipse.emf.ecore.InternalEObject
# import org.eclipse.emf.ecore.impl.ENotificationImpl
# import org.eclipse.emf.ecore.impl.MinimalEObjectImpl

from org.lflang.lf import LFCode

from org.lflang.lf import LfPackage

from org.lflang.lf import Preamble

from org.lflang.lf import Visibility

# 
#  * <!-- begin-user-doc -->
#  * An implementation of the model object '<em><b>Preamble</b></em>'.
#  * <!-- end-user-doc -->
#  * <p>
#  * The following features are implemented:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.impl.PreambleImpl#getVisibility <em>Visibility</em>}</li>
#  *   <li>{@link org.lflang.lf.impl.PreambleImpl#getCode <em>Code</em>}</li>
#  * </ul>
#  *
#  * @generated
#  
class PreambleImpl(MinimalEObjectImpl, Container, Preamble):
    """ generated source for class PreambleImpl """
    #    * The default value of the '{@link #getVisibility() <em>Visibility</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #getVisibility()
    #    * @generated
    #    * @ordered
    #    
    VISIBILITY_EDEFAULT = Visibility.NONE

    #    * The cached value of the '{@link #getVisibility() <em>Visibility</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #getVisibility()
    #    * @generated
    #    * @ordered
    #    
    visibility = VISIBILITY_EDEFAULT

    #    * The cached value of the '{@link #getCode() <em>Code</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #getCode()
    #    * @generated
    #    * @ordered
    #    
    code_ = None

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __init__(self):
        """ generated source for method __init__ """
        super(PreambleImpl, self).__init__()

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eStaticClass(self):
        """ generated source for method eStaticClass """
        return LfPackage.Literals.PREAMBLE

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def getVisibility(self):
        """ generated source for method getVisibility """
        return self.visibility

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def setVisibility(self, newVisibility):
        """ generated source for method setVisibility """
        oldVisibility = self.visibility
        self.visibility = self.VISIBILITY_EDEFAULT if newVisibility == None else newVisibility
        if eNotificationRequired():
            eNotify(ENotificationImpl(self, Notification.SET, LfPackage.PREAMBLE__VISIBILITY, oldVisibility, self.visibility))

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def getCode(self):
        """ generated source for method getCode """
        return self.code_

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def basicSetCode(self, newCode, msgs):
        """ generated source for method basicSetCode """
        oldCode = self.code_
        self.code_ = newCode
        if eNotificationRequired():
            notification = ENotificationImpl(self, Notification.SET, LfPackage.PREAMBLE__CODE, oldCode, newCode)
            if msgs == None:
                msgs = notification
            else:
                msgs.append(notification)
        return msgs

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def setCode(self, newCode):
        """ generated source for method setCode """
        if newCode != self.code_:
            msgs = None
            if self.code_ != None:
                msgs = (self.code_).eInverseRemove(self, EOPPOSITE_FEATURE_BASE - LfPackage.PREAMBLE__CODE, None, msgs)
            if newCode != None:
                msgs = (newCode).eInverseAdd(self, EOPPOSITE_FEATURE_BASE - LfPackage.PREAMBLE__CODE, None, msgs)
            msgs = self.basicSetCode(newCode, msgs)
            if msgs != None:
                msgs.dispatch()
        elif eNotificationRequired():
            eNotify(ENotificationImpl(self, Notification.SET, LfPackage.PREAMBLE__CODE, newCode, newCode))

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eInverseRemove(self, otherEnd, featureID, msgs):
        """ generated source for method eInverseRemove """
        if featureID == LfPackage.PREAMBLE__CODE:
            return self.basicSetCode(None, msgs)
        return super(PreambleImpl, self).eInverseRemove(otherEnd, featureID, msgs)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eGet(self, featureID, resolve, coreType):
        """ generated source for method eGet """
        if featureID == LfPackage.PREAMBLE__VISIBILITY:
            return self.getVisibility()
        elif featureID == LfPackage.PREAMBLE__CODE:
            return self.getCode()
        return super(PreambleImpl, self).eGet(featureID, resolve, coreType)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eSet(self, featureID, newValue):
        """ generated source for method eSet """
        if featureID == LfPackage.PREAMBLE__VISIBILITY:
            self.setVisibility(newValue)
            return
        elif featureID == LfPackage.PREAMBLE__CODE:
            self.setCode(newValue)
            return
        super(PreambleImpl, self).eSet(featureID, newValue)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eUnset(self, featureID):
        """ generated source for method eUnset """
        if featureID == LfPackage.PREAMBLE__VISIBILITY:
            self.setVisibility(self.VISIBILITY_EDEFAULT)
            return
        elif featureID == LfPackage.PREAMBLE__CODE:
            self.setCode(None)
            return
        super(PreambleImpl, self).eUnset(featureID)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eIsSet(self, featureID):
        """ generated source for method eIsSet """
        if featureID == LfPackage.PREAMBLE__VISIBILITY:
            return self.visibility != self.VISIBILITY_EDEFAULT
        elif featureID == LfPackage.PREAMBLE__CODE:
            return self.code_ != None
        return super(PreambleImpl, self).eIsSet(featureID)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __str__(self):
        """ generated source for method toString """
        if eIsProxy():
            return super(PreambleImpl, self).__str__()
        result = StringBuilder(super(PreambleImpl, self).__str__())
        result.append(" (visibility: ")
        result.append(self.visibility)
        result.append(')')
        return result.__str__()

# PreambleImpl
