#!/usr/bin/env python
""" generated source for module STPImpl """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf.impl
# import org.eclipse.emf.common.notify.Notification
# import org.eclipse.emf.common.notify.NotificationChain
# import org.eclipse.emf.ecore.EClass
# import org.eclipse.emf.ecore.InternalEObject
# import org.eclipse.emf.ecore.impl.ENotificationImpl
# import org.eclipse.emf.ecore.impl.MinimalEObjectImpl

from org.lflang.lf import LFCode

from org.lflang.lf import Expression

from org.lflang.lf import LfPackage

from org.lflang.lf import STP

# 
#  * <!-- begin-user-doc -->
#  * An implementation of the model object '<em><b>STP</b></em>'.
#  * <!-- end-user-doc -->
#  * <p>
#  * The following features are implemented:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.impl.STPImpl#getValue <em>Value</em>}</li>
#  *   <li>{@link org.lflang.lf.impl.STPImpl#getCode <em>Code</em>}</li>
#  * </ul>
#  *
#  * @generated
#  
class STPImpl(MinimalEObjectImpl, Container, STP):
    """ generated source for class STPImpl """
    #    * The cached value of the '{@link #getValue() <em>Value</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #getValue()
    #    * @generated
    #    * @ordered
    #    
    value = None

    #    * The cached value of the '{@link #getCode() <em>Code</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #getCode()
    #    * @generated
    #    * @ordered
    #    
    code_ = None

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __init__(self):
        """ generated source for method __init__ """
        super(STPImpl, self).__init__()

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eStaticClass(self):
        """ generated source for method eStaticClass """
        return LfPackage.Literals.STP

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def getValue(self):
        """ generated source for method getValue """
        return self.value

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def basicSetValue(self, newValue, msgs):
        """ generated source for method basicSetValue """
        oldValue = self.value
        self.value = newValue
        if eNotificationRequired():
            notification = ENotificationImpl(self, Notification.SET, LfPackage.STP__VALUE, oldValue, newValue)
            if msgs == None:
                msgs = notification
            else:
                msgs.append(notification)
        return msgs

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def setValue(self, newValue):
        """ generated source for method setValue """
        if newValue != self.value:
            msgs = None
            if self.value != None:
                msgs = (self.value).eInverseRemove(self, EOPPOSITE_FEATURE_BASE - LfPackage.STP__VALUE, None, msgs)
            if newValue != None:
                msgs = (newValue).eInverseAdd(self, EOPPOSITE_FEATURE_BASE - LfPackage.STP__VALUE, None, msgs)
            msgs = self.basicSetValue(newValue, msgs)
            if msgs != None:
                msgs.dispatch()
        elif eNotificationRequired():
            eNotify(ENotificationImpl(self, Notification.SET, LfPackage.STP__VALUE, newValue, newValue))

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def getCode(self):
        """ generated source for method getCode """
        return self.code_

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def basicSetCode(self, newCode, msgs):
        """ generated source for method basicSetCode """
        oldCode = self.code_
        self.code_ = newCode
        if eNotificationRequired():
            notification = ENotificationImpl(self, Notification.SET, LfPackage.STP__CODE, oldCode, newCode)
            if msgs == None:
                msgs = notification
            else:
                msgs.append(notification)
        return msgs

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def setCode(self, newCode):
        """ generated source for method setCode """
        if newCode != self.code_:
            msgs = None
            if self.code_ != None:
                msgs = (self.code_).eInverseRemove(self, EOPPOSITE_FEATURE_BASE - LfPackage.STP__CODE, None, msgs)
            if newCode != None:
                msgs = (newCode).eInverseAdd(self, EOPPOSITE_FEATURE_BASE - LfPackage.STP__CODE, None, msgs)
            msgs = self.basicSetCode(newCode, msgs)
            if msgs != None:
                msgs.dispatch()
        elif eNotificationRequired():
            eNotify(ENotificationImpl(self, Notification.SET, LfPackage.STP__CODE, newCode, newCode))

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eInverseRemove(self, otherEnd, featureID, msgs):
        """ generated source for method eInverseRemove """
        if featureID == LfPackage.STP__VALUE:
            return self.basicSetValue(None, msgs)
        elif featureID == LfPackage.STP__CODE:
            return self.basicSetCode(None, msgs)
        return super(STPImpl, self).eInverseRemove(otherEnd, featureID, msgs)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eGet(self, featureID, resolve, coreType):
        """ generated source for method eGet """
        if featureID == LfPackage.STP__VALUE:
            return self.getValue()
        elif featureID == LfPackage.STP__CODE:
            return self.getCode()
        return super(STPImpl, self).eGet(featureID, resolve, coreType)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eSet(self, featureID, newValue):
        """ generated source for method eSet """
        if featureID == LfPackage.STP__VALUE:
            self.setValue(newValue)
            return
        elif featureID == LfPackage.STP__CODE:
            self.setCode(newValue)
            return
        super(STPImpl, self).eSet(featureID, newValue)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eUnset(self, featureID):
        """ generated source for method eUnset """
        if featureID == LfPackage.STP__VALUE:
            self.setValue(None)
            return
        elif featureID == LfPackage.STP__CODE:
            self.setCode(None)
            return
        super(STPImpl, self).eUnset(featureID)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eIsSet(self, featureID):
        """ generated source for method eIsSet """
        if featureID == LfPackage.STP__VALUE:
            return self.value != None
        elif featureID == LfPackage.STP__CODE:
            return self.code_ != None
        return super(STPImpl, self).eIsSet(featureID)

# STPImpl
