#!/usr/bin/env python
""" generated source for module TargetDeclImpl """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf.impl
# import org.eclipse.emf.common.notify.Notification
# import org.eclipse.emf.common.notify.NotificationChain
# import org.eclipse.emf.ecore.EClass
# import org.eclipse.emf.ecore.InternalEObject
# import org.eclipse.emf.ecore.impl.ENotificationImpl
# import org.eclipse.emf.ecore.impl.MinimalEObjectImpl

from org.lflang.lf import KeyValuePairs

from org.lflang.lf import LfPackage

from org.lflang.lf import TargetDecl

# 
#  * <!-- begin-user-doc -->
#  * An implementation of the model object '<em><b>Target Decl</b></em>'.
#  * <!-- end-user-doc -->
#  * <p>
#  * The following features are implemented:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.impl.TargetDeclImpl#getName <em>Name</em>}</li>
#  *   <li>{@link org.lflang.lf.impl.TargetDeclImpl#getConfig <em>Config</em>}</li>
#  * </ul>
#  *
#  * @generated
#  
class TargetDeclImpl(MinimalEObjectImpl, Container, TargetDecl):
    """ generated source for class TargetDeclImpl """
    #    * The default value of the '{@link #getName() <em>Name</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #getName()
    #    * @generated
    #    * @ordered
    #    
    NAME_EDEFAULT = None

    #    * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #getName()
    #    * @generated
    #    * @ordered
    #    
    name = NAME_EDEFAULT

    #    * The cached value of the '{@link #getConfig() <em>Config</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #getConfig()
    #    * @generated
    #    * @ordered
    #    
    config = None

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __init__(self):
        """ generated source for method __init__ """
        super(TargetDeclImpl, self).__init__()

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eStaticClass(self):
        """ generated source for method eStaticClass """
        return LfPackage.Literals.TARGET_DECL

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def getName(self):
        """ generated source for method getName """
        return self.name

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def setName(self, newName):
        """ generated source for method setName """
        oldName = self.name
        self.name = newName
        if eNotificationRequired():
            eNotify(ENotificationImpl(self, Notification.SET, LfPackage.TARGET_DECL__NAME, oldName, self.name))

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def getConfig(self):
        """ generated source for method getConfig """
        return self.config

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def basicSetConfig(self, newConfig, msgs):
        """ generated source for method basicSetConfig """
        oldConfig = self.config
        self.config = newConfig
        if eNotificationRequired():
            notification = ENotificationImpl(self, Notification.SET, LfPackage.TARGET_DECL__CONFIG, oldConfig, newConfig)
            if msgs == None:
                msgs = notification
            else:
                msgs.append(notification)
        return msgs

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def setConfig(self, newConfig):
        """ generated source for method setConfig """
        if newConfig != self.config:
            msgs = None
            if self.config != None:
                msgs = (self.config).eInverseRemove(self, EOPPOSITE_FEATURE_BASE - LfPackage.TARGET_DECL__CONFIG, None, msgs)
            if newConfig != None:
                msgs = (newConfig).eInverseAdd(self, EOPPOSITE_FEATURE_BASE - LfPackage.TARGET_DECL__CONFIG, None, msgs)
            msgs = self.basicSetConfig(newConfig, msgs)
            if msgs != None:
                msgs.dispatch()
        elif eNotificationRequired():
            eNotify(ENotificationImpl(self, Notification.SET, LfPackage.TARGET_DECL__CONFIG, newConfig, newConfig))

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eInverseRemove(self, otherEnd, featureID, msgs):
        """ generated source for method eInverseRemove """
        if featureID == LfPackage.TARGET_DECL__CONFIG:
            return self.basicSetConfig(None, msgs)
        return super(TargetDeclImpl, self).eInverseRemove(otherEnd, featureID, msgs)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eGet(self, featureID, resolve, coreType):
        """ generated source for method eGet """
        if featureID == LfPackage.TARGET_DECL__NAME:
            return self.__name__
        elif featureID == LfPackage.TARGET_DECL__CONFIG:
            return self.getConfig()
        return super(TargetDeclImpl, self).eGet(featureID, resolve, coreType)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eSet(self, featureID, newValue):
        """ generated source for method eSet """
        if featureID == LfPackage.TARGET_DECL__NAME:
            self.setName(str(newValue))
            return
        elif featureID == LfPackage.TARGET_DECL__CONFIG:
            self.setConfig(newValue)
            return
        super(TargetDeclImpl, self).eSet(featureID, newValue)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eUnset(self, featureID):
        """ generated source for method eUnset """
        if featureID == LfPackage.TARGET_DECL__NAME:
            self.setName(self.NAME_EDEFAULT)
            return
        elif featureID == LfPackage.TARGET_DECL__CONFIG:
            self.setConfig(None)
            return
        super(TargetDeclImpl, self).eUnset(featureID)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eIsSet(self, featureID):
        """ generated source for method eIsSet """
        if featureID == LfPackage.TARGET_DECL__NAME:
            return self.name != None if self.NAME_EDEFAULT == None else not self.NAME_EDEFAULT == self.name
        elif featureID == LfPackage.TARGET_DECL__CONFIG:
            return self.config != None
        return super(TargetDeclImpl, self).eIsSet(featureID)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __str__(self):
        """ generated source for method toString """
        if eIsProxy():
            return super(TargetDeclImpl, self).__str__()
        result = StringBuilder(super(TargetDeclImpl, self).__str__())
        result.append(" (name: ")
        result.append(self.name)
        result.append(')')
        return result.__str__()

# TargetDeclImpl
