#!/usr/bin/env python
""" generated source for module TriggerRefImpl """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf.impl
# import org.eclipse.emf.ecore.EClass
# import org.eclipse.emf.ecore.impl.MinimalEObjectImpl

from org.lflang.lf import LfPackage

from org.lflang.lf import TriggerRef

# 
#  * <!-- begin-user-doc -->
#  * An implementation of the model object '<em><b>Trigger Ref</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * @generated
#  
class TriggerRefImpl(MinimalEObjectImpl, Container, TriggerRef):
    """ generated source for class TriggerRefImpl """
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __init__(self):
        """ generated source for method __init__ """
        super(TriggerRefImpl, self).__init__()

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eStaticClass(self):
        """ generated source for method eStaticClass """
        return LfPackage.Literals.TRIGGER_REF

# TriggerRefImpl
