#!/usr/bin/env python
""" generated source for module TypeParmImpl """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf.impl
# import org.eclipse.emf.common.notify.Notification
# import org.eclipse.emf.common.notify.NotificationChain
# import org.eclipse.emf.ecore.EClass
# import org.eclipse.emf.ecore.InternalEObject
# import org.eclipse.emf.ecore.impl.ENotificationImpl
# import org.eclipse.emf.ecore.impl.MinimalEObjectImpl

from org.lflang.lf import LFCode

from org.lflang.lf import LfPackage

from org.lflang.lf import TypeParm

# 
#  * <!-- begin-user-doc -->
#  * An implementation of the model object '<em><b>Type Parm</b></em>'.
#  * <!-- end-user-doc -->
#  * <p>
#  * The following features are implemented:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.impl.TypeParmImpl#getLiteral <em>Literal</em>}</li>
#  *   <li>{@link org.lflang.lf.impl.TypeParmImpl#getCode <em>Code</em>}</li>
#  * </ul>
#  *
#  * @generated
#  
class TypeParmImpl(MinimalEObjectImpl, Container, TypeParm):
    """ generated source for class TypeParmImpl """
    #    * The default value of the '{@link #getLiteral() <em>Literal</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #getLiteral()
    #    * @generated
    #    * @ordered
    #    
    LITERAL_EDEFAULT = None

    #    * The cached value of the '{@link #getLiteral() <em>Literal</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #getLiteral()
    #    * @generated
    #    * @ordered
    #    
    literal = LITERAL_EDEFAULT

    #    * The cached value of the '{@link #getCode() <em>Code</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #getCode()
    #    * @generated
    #    * @ordered
    #    
    code_ = None

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __init__(self):
        """ generated source for method __init__ """
        super(TypeParmImpl, self).__init__()

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eStaticClass(self):
        """ generated source for method eStaticClass """
        return LfPackage.Literals.TYPE_PARM

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def getLiteral(self):
        """ generated source for method getLiteral """
        return self.literal

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def setLiteral(self, newLiteral):
        """ generated source for method setLiteral """
        oldLiteral = self.literal
        self.literal = newLiteral
        if eNotificationRequired():
            eNotify(ENotificationImpl(self, Notification.SET, LfPackage.TYPE_PARM__LITERAL, oldLiteral, self.literal))

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def getCode(self):
        """ generated source for method getCode """
        return self.code_

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def basicSetCode(self, newCode, msgs):
        """ generated source for method basicSetCode """
        oldCode = self.code_
        self.code_ = newCode
        if eNotificationRequired():
            notification = ENotificationImpl(self, Notification.SET, LfPackage.TYPE_PARM__CODE, oldCode, newCode)
            if msgs == None:
                msgs = notification
            else:
                msgs.append(notification)
        return msgs

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def setCode(self, newCode):
        """ generated source for method setCode """
        if newCode != self.code_:
            msgs = None
            if self.code_ != None:
                msgs = (self.code_).eInverseRemove(self, EOPPOSITE_FEATURE_BASE - LfPackage.TYPE_PARM__CODE, None, msgs)
            if newCode != None:
                msgs = (newCode).eInverseAdd(self, EOPPOSITE_FEATURE_BASE - LfPackage.TYPE_PARM__CODE, None, msgs)
            msgs = self.basicSetCode(newCode, msgs)
            if msgs != None:
                msgs.dispatch()
        elif eNotificationRequired():
            eNotify(ENotificationImpl(self, Notification.SET, LfPackage.TYPE_PARM__CODE, newCode, newCode))

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eInverseRemove(self, otherEnd, featureID, msgs):
        """ generated source for method eInverseRemove """
        if featureID == LfPackage.TYPE_PARM__CODE:
            return self.basicSetCode(None, msgs)
        return super(TypeParmImpl, self).eInverseRemove(otherEnd, featureID, msgs)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eGet(self, featureID, resolve, coreType):
        """ generated source for method eGet """
        if featureID == LfPackage.TYPE_PARM__LITERAL:
            return self.getLiteral()
        elif featureID == LfPackage.TYPE_PARM__CODE:
            return self.getCode()
        return super(TypeParmImpl, self).eGet(featureID, resolve, coreType)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eSet(self, featureID, newValue):
        """ generated source for method eSet """
        if featureID == LfPackage.TYPE_PARM__LITERAL:
            self.setLiteral(str(newValue))
            return
        elif featureID == LfPackage.TYPE_PARM__CODE:
            self.setCode(newValue)
            return
        super(TypeParmImpl, self).eSet(featureID, newValue)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eUnset(self, featureID):
        """ generated source for method eUnset """
        if featureID == LfPackage.TYPE_PARM__LITERAL:
            self.setLiteral(self.LITERAL_EDEFAULT)
            return
        elif featureID == LfPackage.TYPE_PARM__CODE:
            self.setCode(None)
            return
        super(TypeParmImpl, self).eUnset(featureID)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def eIsSet(self, featureID):
        """ generated source for method eIsSet """
        if featureID == LfPackage.TYPE_PARM__LITERAL:
            return self.literal != None if self.LITERAL_EDEFAULT == None else not self.LITERAL_EDEFAULT == self.literal
        elif featureID == LfPackage.TYPE_PARM__CODE:
            return self.code_ != None
        return super(TypeParmImpl, self).eIsSet(featureID)

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __str__(self):
        """ generated source for method toString """
        if eIsProxy():
            return super(TypeParmImpl, self).__str__()
        result = StringBuilder(super(TypeParmImpl, self).__str__())
        result.append(" (literal: ")
        result.append(self.literal)
        result.append(')')
        return result.__str__()

# TypeParmImpl
