#!/usr/bin/env python
""" generated source for module Messages """
# 
#  * generated by Xtext 2.25.0
#  
# package: org.lflang.ui.wizard
# import org.eclipse.osgi.util.NLS

class Messages(NLS):
    """ generated source for class Messages """
    BUNDLE_NAME = "org.lflang.ui.wizard.messages"

    # $NON-NLS-1$
    DefaultProject_Label = None
    DefaultProject_Description = None
    HelloWorldProject_Label = None
    HelloWorldProject_Description = None
    InteractiveProject_Label = None
    InteractiveProject_Description = None
    WebServerProject_Label = None
    WebServerProject_Description = None
    ReflexGameProject_Label = None
    ReflexGameProject_Description = None
    FederatedProject_Label = None
    FederatedProject_Description = None
    ParallelProject_Label = None
    ParallelProject_Description = None
    PipelineProject_Label = None
    PipelineProject_Description = None

    #  initialize resource bundle
    def __init__(self):
        """ generated source for method __init__ """
        super(Messages, self).__init__()
