#!/usr/bin/env python
""" generated source for module LFLabelProvider """
# 
#  * generated by Xtext 2.23.0
#  
# package: org.lflang.ui.labeling
# import com.google.inject.Inject
# import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider
# import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider

# 
#  * Provides labels for EObjects.
#  * 
#  * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
#  
class LFLabelProvider(DefaultEObjectLabelProvider):
    """ generated source for class LFLabelProvider """
    def __init__(self, delegate):
        """ generated source for method __init__ """
        super(LFLabelProvider, self).__init__(delegate)

    #  Labels and icons can be computed like this:
    # 	String text(Greeting ele) {
    # 		return "A greeting to " + ele.__name__;
    # 	}
    # 	String image(Greeting ele) {
    # 		return "Greeting.gif";
    # 	}
