#!/usr/bin/env python
""" generated source for module LFOutlineTreeProvider """
# 
#  * generated by Xtext 2.23.0
#  
# package: org.lflang.ui.outline
# import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

# 
#  * Customization of the default outline structure.
#  *
#  * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
#  
class LFOutlineTreeProvider(DefaultOutlineTreeProvider):
    """ generated source for class LFOutlineTreeProvider """
