#!/usr/bin/env python
""" generated source for module AbstractLFValidator """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.validation
# import java.util.ArrayList
# import java.util.List
# import org.eclipse.emf.ecore.EPackage
# import org.eclipse.xtext.validation.AbstractDeclarativeValidator
# import org.eclipse.xtext.validation.ComposedChecks
# import org.eclipse.xtext.validation.NamesAreUniqueValidator

@ComposedChecks(validators=NamesAreUniqueValidator.__class__)
class AbstractLFValidator(AbstractDeclarativeValidator):
    """ generated source for class AbstractLFValidator """
    def getEPackages(self):
        """ generated source for method getEPackages """
        result = []
        result.append(eINSTANCE)
        return result
