#!/usr/bin/env python
""" generated source for module LFConfigurableIssueCodesProvider """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.validation
# import org.eclipse.xtext.preferences.PreferenceKey
# import org.eclipse.xtext.util.IAcceptor
# import org.eclipse.xtext.validation.ConfigurableIssueCodesProvider
# import org.eclipse.xtext.validation.SeverityConverter

class LFConfigurableIssueCodesProvider(ConfigurableIssueCodesProvider):
    """ generated source for class LFConfigurableIssueCodesProvider """
    ISSUE_CODE_PREFIX = "org.lflang."
    DEPRECATED_MODEL_PART = ISSUE_CODE_PREFIX + "deprecatedModelPart"

    def initialize(self, acceptor):
        """ generated source for method initialize """
        super(LFConfigurableIssueCodesProvider, self).initialize(acceptor)
        acceptor.accept(create(self.DEPRECATED_MODEL_PART, SeverityConverter.SEVERITY_WARNING))
