#!/usr/bin/env python
""" generated source for module AbstractLFScopeProvider """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.scoping
# import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider

class DelegatingScopeProvider:
    pass


class AbstractLFScopeProvider(DelegatingScopeProvider):
    """ generated source for class AbstractLFScopeProvider """
