#!/usr/bin/env python
""" generated source for module LFStandaloneSetup """
# 
#  * generated by Xtext 2.25.0
#  
# package: org.lflang
# import org.eclipse.xtext.util.Modules2
# import com.google.inject.Guice
# import com.google.inject.Injector
# import com.google.inject.Module

# 
#  * Initialization support for running Xtext languages without
#  * Equinox extension registry.
#  *
#  * See {@link LFRuntimeModule}, the base Guice module for LF services.
#  
class LFStandaloneSetup(LFStandaloneSetupGenerated):
    """ generated source for class LFStandaloneSetup """
    module_ = None

    @overloaded
    def __init__(self):
        """ generated source for method __init__ """
        super(LFStandaloneSetup, self).__init__()
        self.module_ = LFRuntimeModule()

    @__init__.register(object, A)
    def __init___0(self, *modules):
        """ generated source for method __init___0 """
        super(LFStandaloneSetup, self).__init__()
        self.module_ = Modules2.mixin(modules)

    def createInjector(self):
        """ generated source for method createInjector """
        return Guice.createInjector(self.module_)
