#!/usr/bin/env python
""" generated source for module ArraySpec """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# import org.eclipse.emf.ecore.EObject

# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>Array Spec</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * <p>
#  * The following features are supported:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.ArraySpec#isOfVariableLength <em>Of Variable Length</em>}</li>
#  *   <li>{@link org.lflang.lf.ArraySpec#getLength <em>Length</em>}</li>
#  * </ul>
#  *
#  * @see org.lflang.lf.LfPackage#getArraySpec()
#  * @model
#  * @generated
#  
class ArraySpec(EObject):
    """ generated source for interface ArraySpec """
    __metaclass__ = ABCMeta
    #    * Returns the value of the '<em><b>Of Variable Length</b></em>' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Of Variable Length</em>' attribute.
    #    * @see #setOfVariableLength(boolean)
    #    * @see org.lflang.lf.LfPackage#getArraySpec_OfVariableLength()
    #    * @model
    #    * @generated
    #    
    @abstractmethod
    def isOfVariableLength(self):
        """ generated source for method isOfVariableLength """

    #    * Sets the value of the '{@link org.lflang.lf.ArraySpec#isOfVariableLength <em>Of Variable Length</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Of Variable Length</em>' attribute.
    #    * @see #isOfVariableLength()
    #    * @generated
    #    
    @abstractmethod
    def setOfVariableLength(self, value):
        """ generated source for method setOfVariableLength """

    #    * Returns the value of the '<em><b>Length</b></em>' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Length</em>' attribute.
    #    * @see #setLength(int)
    #    * @see org.lflang.lf.LfPackage#getArraySpec_Length()
    #    * @model
    #    * @generated
    #    
    @abstractmethod
    def getLength(self):
        """ generated source for method getLength """

    #    * Sets the value of the '{@link org.lflang.lf.ArraySpec#getLength <em>Length</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Length</em>' attribute.
    #    * @see #getLength()
    #    * @generated
    #    
    @abstractmethod
    def setLength(self, value):
        """ generated source for method setLength """

#  ArraySpec
