#!/usr/bin/env python
""" generated source for module BuiltinTriggerRef """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>Builtin Trigger Ref</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * <p>
#  * The following features are supported:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.BuiltinTriggerRef#getType <em>Type</em>}</li>
#  * </ul>
#  *
#  * @see org.lflang.lf.LfPackage#getBuiltinTriggerRef()
#  * @model
#  * @generated
#  
class BuiltinTriggerRef(TriggerRef):
    """ generated source for interface BuiltinTriggerRef """
    __metaclass__ = ABCMeta
    #    * Returns the value of the '<em><b>Type</b></em>' attribute.
    #    * The literals are from the enumeration {@link org.lflang.lf.BuiltinTrigger}.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Type</em>' attribute.
    #    * @see org.lflang.lf.BuiltinTrigger
    #    * @see #setType(BuiltinTrigger)
    #    * @see org.lflang.lf.LfPackage#getBuiltinTriggerRef_Type()
    #    * @model
    #    * @generated
    #    
    @abstractmethod
    def getType(self):
        """ generated source for method getType """

    #    * Sets the value of the '{@link org.lflang.lf.BuiltinTriggerRef#getType <em>Type</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Type</em>' attribute.
    #    * @see org.lflang.lf.BuiltinTrigger
    #    * @see #getType()
    #    * @generated
    #    
    @abstractmethod
    def setType(self, value):
        """ generated source for method setType """

#  BuiltinTriggerRef
