#!/usr/bin/env python
""" generated source for module Expression """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# import org.eclipse.emf.ecore.EObject

# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>Expression</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  *
#  * @see org.lflang.lf.LfPackage#getExpression()
#  * @model
#  * @generated
#  
class Expression(EObject):
    """ generated source for interface Expression """
    __metaclass__ = ABCMeta

#  Expression
