#!/usr/bin/env python
""" generated source for module ImportedReactor """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>Imported Reactor</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * <p>
#  * The following features are supported:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.ImportedReactor#getReactorClass <em>Reactor Class</em>}</li>
#  * </ul>
#  *
#  * @see org.lflang.lf.LfPackage#getImportedReactor()
#  * @model
#  * @generated
#  
class ImportedReactor(ReactorDecl):
    """ generated source for interface ImportedReactor """
    __metaclass__ = ABCMeta
    #    * Returns the value of the '<em><b>Reactor Class</b></em>' reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Reactor Class</em>' reference.
    #    * @see #setReactorClass(Reactor)
    #    * @see org.lflang.lf.LfPackage#getImportedReactor_ReactorClass()
    #    * @model
    #    * @generated
    #    
    @abstractmethod
    def getReactorClass(self):
        """ generated source for method getReactorClass """

    #    * Sets the value of the '{@link org.lflang.lf.ImportedReactor#getReactorClass <em>Reactor Class</em>}' reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Reactor Class</em>' reference.
    #    * @see #getReactorClass()
    #    * @generated
    #    
    @abstractmethod
    def setReactorClass(self, value):
        """ generated source for method setReactorClass """

#  ImportedReactor
