#!/usr/bin/env python
""" generated source for module IPV6Host """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>IPV6 Host</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  *
#  * @see org.lflang.lf.LfPackage#getIPV6Host()
#  * @model
#  * @generated
#  
class IPV6Host(Host):
    """ generated source for interface IPV6Host """
    __metaclass__ = ABCMeta

#  IPV6Host
