#!/usr/bin/env python
""" generated source for module KeyValuePairs """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# import org.eclipse.emf.common.util.EList
# import org.eclipse.emf.ecore.EObject

# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>Key Value Pairs</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * <p>
#  * The following features are supported:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.KeyValuePairs#getPairs <em>Pairs</em>}</li>
#  * </ul>
#  *
#  * @see org.lflang.lf.LfPackage#getKeyValuePairs()
#  * @model
#  * @generated
#  
class KeyValuePairs(EObject):
    """ generated source for interface KeyValuePairs """
    __metaclass__ = ABCMeta
    #    * Returns the value of the '<em><b>Pairs</b></em>' containment reference list.
    #    * The list contents are of type {@link org.lflang.lf.KeyValuePair}.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Pairs</em>' containment reference list.
    #    * @see org.lflang.lf.LfPackage#getKeyValuePairs_Pairs()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getPairs(self):
        """ generated source for method getPairs """

#  KeyValuePairs
