#!/usr/bin/env python
""" generated source for module Code """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>Code</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * <p>
#  * The following features are supported:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.Code#getBody <em>Body</em>}</li>
#  * </ul>
#  *
#  * @see org.lflang.lf.LfPackage#getCode()
#  * @model
#  * @generated
#  
class Code(Expression):
    """ generated source for interface Code """
    __metaclass__ = ABCMeta
    #    * Returns the value of the '<em><b>Body</b></em>' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Body</em>' attribute.
    #    * @see #setBody(String)
    #    * @see org.lflang.lf.LfPackage#getCode_Body()
    #    * @model
    #    * @generated
    #    
    @abstractmethod
    def getBody(self):
        """ generated source for method getBody """

    #    * Sets the value of the '{@link org.lflang.lf.Code#getBody <em>Body</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Body</em>' attribute.
    #    * @see #getBody()
    #    * @generated
    #    
    @abstractmethod
    def setBody(self, value):
        """ generated source for method setBody """

#  Code
