#!/usr/bin/env python
""" generated source for module Literal """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>Literal</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * <p>
#  * The following features are supported:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.Literal#getLiteral <em>Literal</em>}</li>
#  * </ul>
#  *
#  * @see org.lflang.lf.LfPackage#getLiteral()
#  * @model
#  * @generated
#  
class Literal(Expression):
    """ generated source for interface Literal """
    __metaclass__ = ABCMeta
    #    * Returns the value of the '<em><b>Literal</b></em>' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Literal</em>' attribute.
    #    * @see #setLiteral(String)
    #    * @see org.lflang.lf.LfPackage#getLiteral_Literal()
    #    * @model
    #    * @generated
    #    
    @abstractmethod
    def getLiteral(self):
        """ generated source for method getLiteral """

    #    * Sets the value of the '{@link org.lflang.lf.Literal#getLiteral <em>Literal</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Literal</em>' attribute.
    #    * @see #getLiteral()
    #    * @generated
    #    
    @abstractmethod
    def setLiteral(self, value):
        """ generated source for method setLiteral """

#  Literal
