#!/usr/bin/env python
""" generated source for module ModeTransition """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# import java.util.Arrays
# import java.util.Collections
# import java.util.List
# import org.eclipse.emf.common.util.Enumerator
from include.overloading import overloaded
# 
#  * <!-- begin-user-doc -->
#  * A representation of the literals of the enumeration '<em><b>Mode Transition</b></em>',
#  * and utility methods for working with them.
#  * <!-- end-user-doc -->
#  * @see org.lflang.lf.LfPackage#getModeTransition()
#  * @model
#  * @generated
#  
class ModeTransition:
    """ generated source for enum ModeTransition """
    #    * The '<em><b>RESET</b></em>' literal value.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #RESET
    #    * @model literal="reset"
    #    * @generated
    #    * @ordered
    #    
    RESET_VALUE = 0

    #    * The '<em><b>HISTORY</b></em>' literal value.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #HISTORY
    #    * @model literal="history"
    #    * @generated
    #    * @ordered
    #    
    HISTORY_VALUE = 1

    #    * An array of all the '<em><b>Mode Transition</b></em>' enumerators.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    VALUES_ARRAY = [None] * 

    #    * A public read-only list of all the '<em><b>Mode Transition</b></em>' enumerators.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY))

    #    * Returns the '<em><b>Mode Transition</b></em>' literal with the specified literal value.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param literal the literal.
    #    * @return the matching enumerator or <code>null</code>.
    #    * @generated
    #    
    @classmethod
    @overloaded
    def get(cls, literal):
        """ generated source for method get """
        i = 0
        while len(VALUES_ARRAY):
            result = cls.VALUES_ARRAY[i]
            if result.__str__() == literal:
                return result
            i += 1
        return None

    #    * Returns the '<em><b>Mode Transition</b></em>' literal with the specified name.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param name the name.
    #    * @return the matching enumerator or <code>null</code>.
    #    * @generated
    #    
    @classmethod
    def getByName(cls, name):
        """ generated source for method getByName """
        i = 0
        while len(VALUES_ARRAY):
            result = cls.VALUES_ARRAY[i]
            if result.__name__ == name:
                return result
            i += 1
        return None

    #    * Returns the '<em><b>Mode Transition</b></em>' literal with the specified integer value.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the integer value.
    #    * @return the matching enumerator or <code>null</code>.
    #    * @generated
    #    
    @classmethod
    @get.register(object, int)
    def get_0(cls, value):
        """ generated source for method get_0 """
        if value == cls.RESET_VALUE:
            return RESET
        elif value == cls.HISTORY_VALUE:
            return HISTORY
        return None

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    value = int()

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    name = None

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    literal = None

    #    * Only this class can construct instances.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __init__(self, value, name, literal):
        """ generated source for method __init__ """
        super(ModeTransition, self).__init__()
        self.value = value
        self.name = name
        self.literal = literal

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def getValue(self):
        """ generated source for method getValue """
        return self.value

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def getName(self):
        """ generated source for method getName """
        return self.name

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def getLiteral(self):
        """ generated source for method getLiteral """
        return self.literal

    #    * Returns the literal value of the enumerator, which is its string representation.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __str__(self):
        """ generated source for method toString """
        return self.literal

ModeTransition.RESET = ModeTransition(0, "RESET", "reset")

ModeTransition.HISTORY = ModeTransition(1, "HISTORY", "history")

# ModeTransition
