#!/usr/bin/env python
""" generated source for module NamedHost """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>Named Host</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  *
#  * @see org.lflang.lf.LfPackage#getNamedHost()
#  * @model
#  * @generated
#  
class NamedHost(Host):
    """ generated source for interface NamedHost """
    __metaclass__ = ABCMeta

#  NamedHost
