#!/usr/bin/env python
""" generated source for module Reaction """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# import org.eclipse.emf.common.util.EList
# import org.eclipse.emf.ecore.EObject

# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>Reaction</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * <p>
#  * The following features are supported:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.Reaction#getAttributes <em>Attributes</em>}</li>
#  *   <li>{@link org.lflang.lf.Reaction#isMutation <em>Mutation</em>}</li>
#  *   <li>{@link org.lflang.lf.Reaction#getTriggers <em>Triggers</em>}</li>
#  *   <li>{@link org.lflang.lf.Reaction#getSources <em>Sources</em>}</li>
#  *   <li>{@link org.lflang.lf.Reaction#getEffects <em>Effects</em>}</li>
#  *   <li>{@link org.lflang.lf.Reaction#getCode <em>Code</em>}</li>
#  *   <li>{@link org.lflang.lf.Reaction#getStp <em>Stp</em>}</li>
#  *   <li>{@link org.lflang.lf.Reaction#getDeadline <em>Deadline</em>}</li>
#  * </ul>
#  *
#  * @see org.lflang.lf.LfPackage#getReaction()
#  * @model
#  * @generated
#  
class Reaction(EObject):
    """ generated source for interface Reaction """
    __metaclass__ = ABCMeta
    #    * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
    #    * The list contents are of type {@link org.lflang.lf.Attribute}.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Attributes</em>' containment reference list.
    #    * @see org.lflang.lf.LfPackage#getReaction_Attributes()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getAttributes(self):
        """ generated source for method getAttributes """

    #    * Returns the value of the '<em><b>Mutation</b></em>' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Mutation</em>' attribute.
    #    * @see #setMutation(boolean)
    #    * @see org.lflang.lf.LfPackage#getReaction_Mutation()
    #    * @model
    #    * @generated
    #    
    @abstractmethod
    def isMutation(self):
        """ generated source for method isMutation """

    #    * Sets the value of the '{@link org.lflang.lf.Reaction#isMutation <em>Mutation</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Mutation</em>' attribute.
    #    * @see #isMutation()
    #    * @generated
    #    
    @abstractmethod
    def setMutation(self, value):
        """ generated source for method setMutation """

    #    * Returns the value of the '<em><b>Triggers</b></em>' containment reference list.
    #    * The list contents are of type {@link org.lflang.lf.TriggerRef}.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Triggers</em>' containment reference list.
    #    * @see org.lflang.lf.LfPackage#getReaction_Triggers()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getTriggers(self):
        """ generated source for method getTriggers """

    #    * Returns the value of the '<em><b>Sources</b></em>' containment reference list.
    #    * The list contents are of type {@link org.lflang.lf.VarRef}.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Sources</em>' containment reference list.
    #    * @see org.lflang.lf.LfPackage#getReaction_Sources()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getSources(self):
        """ generated source for method getSources """

    #    * Returns the value of the '<em><b>Effects</b></em>' containment reference list.
    #    * The list contents are of type {@link org.lflang.lf.VarRef}.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Effects</em>' containment reference list.
    #    * @see org.lflang.lf.LfPackage#getReaction_Effects()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getEffects(self):
        """ generated source for method getEffects """

    #    * Returns the value of the '<em><b>Code</b></em>' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Code</em>' containment reference.
    #    * @see #setCode(Code)
    #    * @see org.lflang.lf.LfPackage#getReaction_Code()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getCode(self):
        """ generated source for method getCode """

    #    * Sets the value of the '{@link org.lflang.lf.Reaction#getCode <em>Code</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Code</em>' containment reference.
    #    * @see #getCode()
    #    * @generated
    #    
    @abstractmethod
    def setCode(self, value):
        """ generated source for method setCode """

    #    * Returns the value of the '<em><b>Stp</b></em>' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Stp</em>' containment reference.
    #    * @see #setStp(STP)
    #    * @see org.lflang.lf.LfPackage#getReaction_Stp()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getStp(self):
        """ generated source for method getStp """

    #    * Sets the value of the '{@link org.lflang.lf.Reaction#getStp <em>Stp</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Stp</em>' containment reference.
    #    * @see #getStp()
    #    * @generated
    #    
    @abstractmethod
    def setStp(self, value):
        """ generated source for method setStp """

    #    * Returns the value of the '<em><b>Deadline</b></em>' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Deadline</em>' containment reference.
    #    * @see #setDeadline(Deadline)
    #    * @see org.lflang.lf.LfPackage#getReaction_Deadline()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getDeadline(self):
        """ generated source for method getDeadline """

    #    * Sets the value of the '{@link org.lflang.lf.Reaction#getDeadline <em>Deadline</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Deadline</em>' containment reference.
    #    * @see #getDeadline()
    #    * @generated
    #    
    @abstractmethod
    def setDeadline(self, value):
        """ generated source for method setDeadline """

#  Reaction
