#!/usr/bin/env python
""" generated source for module Serializer """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# import org.eclipse.emf.ecore.EObject

# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>Serializer</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * <p>
#  * The following features are supported:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.Serializer#getType <em>Type</em>}</li>
#  * </ul>
#  *
#  * @see org.lflang.lf.LfPackage#getSerializer()
#  * @model
#  * @generated
#  
class Serializer(EObject):
    """ generated source for interface Serializer """
    __metaclass__ = ABCMeta
    #    * Returns the value of the '<em><b>Type</b></em>' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Type</em>' attribute.
    #    * @see #setType(String)
    #    * @see org.lflang.lf.LfPackage#getSerializer_Type()
    #    * @model
    #    * @generated
    #    
    @abstractmethod
    def getType(self):
        """ generated source for method getType """

    #    * Sets the value of the '{@link org.lflang.lf.Serializer#getType <em>Type</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Type</em>' attribute.
    #    * @see #getType()
    #    * @generated
    #    
    @abstractmethod
    def setType(self, value):
        """ generated source for method setType """

#  Serializer
