#!/usr/bin/env python
""" generated source for module StateVar """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# import org.eclipse.emf.common.util.EList
# import org.eclipse.emf.ecore.EObject

# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>State Var</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * <p>
#  * The following features are supported:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.StateVar#getAttributes <em>Attributes</em>}</li>
#  *   <li>{@link org.lflang.lf.StateVar#isReset <em>Reset</em>}</li>
#  *   <li>{@link org.lflang.lf.StateVar#getName <em>Name</em>}</li>
#  *   <li>{@link org.lflang.lf.StateVar#getType <em>Type</em>}</li>
#  *   <li>{@link org.lflang.lf.StateVar#getParens <em>Parens</em>}</li>
#  *   <li>{@link org.lflang.lf.StateVar#getInit <em>Init</em>}</li>
#  *   <li>{@link org.lflang.lf.StateVar#getBraces <em>Braces</em>}</li>
#  * </ul>
#  *
#  * @see org.lflang.lf.LfPackage#getStateVar()
#  * @model
#  * @generated
#  
class StateVar(EObject):
    """ generated source for interface StateVar """
    __metaclass__ = ABCMeta
    #    * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
    #    * The list contents are of type {@link org.lflang.lf.Attribute}.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Attributes</em>' containment reference list.
    #    * @see org.lflang.lf.LfPackage#getStateVar_Attributes()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getAttributes(self):
        """ generated source for method getAttributes """

    #    * Returns the value of the '<em><b>Reset</b></em>' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Reset</em>' attribute.
    #    * @see #setReset(boolean)
    #    * @see org.lflang.lf.LfPackage#getStateVar_Reset()
    #    * @model
    #    * @generated
    #    
    @abstractmethod
    def isReset(self):
        """ generated source for method isReset """

    #    * Sets the value of the '{@link org.lflang.lf.StateVar#isReset <em>Reset</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Reset</em>' attribute.
    #    * @see #isReset()
    #    * @generated
    #    
    @abstractmethod
    def setReset(self, value):
        """ generated source for method setReset """

    #    * Returns the value of the '<em><b>Name</b></em>' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Name</em>' attribute.
    #    * @see #setName(String)
    #    * @see org.lflang.lf.LfPackage#getStateVar_Name()
    #    * @model
    #    * @generated
    #    
    @abstractmethod
    def getName(self):
        """ generated source for method getName """

    #    * Sets the value of the '{@link org.lflang.lf.StateVar#getName <em>Name</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Name</em>' attribute.
    #    * @see #getName()
    #    * @generated
    #    
    @abstractmethod
    def setName(self, value):
        """ generated source for method setName """

    #    * Returns the value of the '<em><b>Type</b></em>' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Type</em>' containment reference.
    #    * @see #setType(Type)
    #    * @see org.lflang.lf.LfPackage#getStateVar_Type()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getType(self):
        """ generated source for method getType """

    #    * Sets the value of the '{@link org.lflang.lf.StateVar#getType <em>Type</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Type</em>' containment reference.
    #    * @see #getType()
    #    * @generated
    #    
    @abstractmethod
    def setType(self, value):
        """ generated source for method setType """

    #    * Returns the value of the '<em><b>Parens</b></em>' attribute list.
    #    * The list contents are of type {@link java.lang.String}.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Parens</em>' attribute list.
    #    * @see org.lflang.lf.LfPackage#getStateVar_Parens()
    #    * @model unique="false"
    #    * @generated
    #    
    @abstractmethod
    def getParens(self):
        """ generated source for method getParens """

    #    * Returns the value of the '<em><b>Init</b></em>' containment reference list.
    #    * The list contents are of type {@link org.lflang.lf.Expression}.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Init</em>' containment reference list.
    #    * @see org.lflang.lf.LfPackage#getStateVar_Init()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getInit(self):
        """ generated source for method getInit """

    #    * Returns the value of the '<em><b>Braces</b></em>' attribute list.
    #    * The list contents are of type {@link java.lang.String}.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Braces</em>' attribute list.
    #    * @see org.lflang.lf.LfPackage#getStateVar_Braces()
    #    * @model unique="false"
    #    * @generated
    #    
    @abstractmethod
    def getBraces(self):
        """ generated source for method getBraces """

#  StateVar
