#!/usr/bin/env python
""" generated source for module STP """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# import org.eclipse.emf.ecore.EObject

# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>STP</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * <p>
#  * The following features are supported:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.STP#getValue <em>Value</em>}</li>
#  *   <li>{@link org.lflang.lf.STP#getCode <em>Code</em>}</li>
#  * </ul>
#  *
#  * @see org.lflang.lf.LfPackage#getSTP()
#  * @model
#  * @generated
#  
class STP(EObject):
    """ generated source for interface STP """
    __metaclass__ = ABCMeta
    #    * Returns the value of the '<em><b>Value</b></em>' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Value</em>' containment reference.
    #    * @see #setValue(Expression)
    #    * @see org.lflang.lf.LfPackage#getSTP_Value()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getValue(self):
        """ generated source for method getValue """

    #    * Sets the value of the '{@link org.lflang.lf.STP#getValue <em>Value</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Value</em>' containment reference.
    #    * @see #getValue()
    #    * @generated
    #    
    @abstractmethod
    def setValue(self, value):
        """ generated source for method setValue """

    #    * Returns the value of the '<em><b>Code</b></em>' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Code</em>' containment reference.
    #    * @see #setCode(Code)
    #    * @see org.lflang.lf.LfPackage#getSTP_Code()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getCode(self):
        """ generated source for method getCode """

    #    * Sets the value of the '{@link org.lflang.lf.STP#getCode <em>Code</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Code</em>' containment reference.
    #    * @see #getCode()
    #    * @generated
    #    
    @abstractmethod
    def setCode(self, value):
        """ generated source for method setCode """

#  STP
