#!/usr/bin/env python
""" generated source for module TargetDecl """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# import org.eclipse.emf.ecore.EObject

# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>Target Decl</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * <p>
#  * The following features are supported:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.TargetDecl#getName <em>Name</em>}</li>
#  *   <li>{@link org.lflang.lf.TargetDecl#getConfig <em>Config</em>}</li>
#  * </ul>
#  *
#  * @see org.lflang.lf.LfPackage#getTargetDecl()
#  * @model
#  * @generated
#  
class TargetDecl(EObject):
    """ generated source for interface TargetDecl """
    __metaclass__ = ABCMeta
    #    * Returns the value of the '<em><b>Name</b></em>' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Name</em>' attribute.
    #    * @see #setName(String)
    #    * @see org.lflang.lf.LfPackage#getTargetDecl_Name()
    #    * @model
    #    * @generated
    #    
    @abstractmethod
    def getName(self):
        """ generated source for method getName """

    #    * Sets the value of the '{@link org.lflang.lf.TargetDecl#getName <em>Name</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Name</em>' attribute.
    #    * @see #getName()
    #    * @generated
    #    
    @abstractmethod
    def setName(self, value):
        """ generated source for method setName """

    #    * Returns the value of the '<em><b>Config</b></em>' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Config</em>' containment reference.
    #    * @see #setConfig(KeyValuePairs)
    #    * @see org.lflang.lf.LfPackage#getTargetDecl_Config()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getConfig(self):
        """ generated source for method getConfig """

    #    * Sets the value of the '{@link org.lflang.lf.TargetDecl#getConfig <em>Config</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Config</em>' containment reference.
    #    * @see #getConfig()
    #    * @generated
    #    
    @abstractmethod
    def setConfig(self, value):
        """ generated source for method setConfig """

#  TargetDecl
