#!/usr/bin/env python
""" generated source for module Timer """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# import org.eclipse.emf.common.util.EList

# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>Timer</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * <p>
#  * The following features are supported:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.Timer#getAttributes <em>Attributes</em>}</li>
#  *   <li>{@link org.lflang.lf.Timer#getOffset <em>Offset</em>}</li>
#  *   <li>{@link org.lflang.lf.Timer#getPeriod <em>Period</em>}</li>
#  * </ul>
#  *
#  * @see org.lflang.lf.LfPackage#getTimer()
#  * @model
#  * @generated
#  
class Timer(Variable):
    """ generated source for interface Timer """
    __metaclass__ = ABCMeta
    #    * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
    #    * The list contents are of type {@link org.lflang.lf.Attribute}.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Attributes</em>' containment reference list.
    #    * @see org.lflang.lf.LfPackage#getTimer_Attributes()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getAttributes(self):
        """ generated source for method getAttributes """

    #    * Returns the value of the '<em><b>Offset</b></em>' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Offset</em>' containment reference.
    #    * @see #setOffset(Expression)
    #    * @see org.lflang.lf.LfPackage#getTimer_Offset()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getOffset(self):
        """ generated source for method getOffset """

    #    * Sets the value of the '{@link org.lflang.lf.Timer#getOffset <em>Offset</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Offset</em>' containment reference.
    #    * @see #getOffset()
    #    * @generated
    #    
    @abstractmethod
    def setOffset(self, value):
        """ generated source for method setOffset """

    #    * Returns the value of the '<em><b>Period</b></em>' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Period</em>' containment reference.
    #    * @see #setPeriod(Expression)
    #    * @see org.lflang.lf.LfPackage#getTimer_Period()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getPeriod(self):
        """ generated source for method getPeriod """

    #    * Sets the value of the '{@link org.lflang.lf.Timer#getPeriod <em>Period</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Period</em>' containment reference.
    #    * @see #getPeriod()
    #    * @generated
    #    
    @abstractmethod
    def setPeriod(self, value):
        """ generated source for method setPeriod """

#  Timer
