#!/usr/bin/env python
""" generated source for module Time """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>Time</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * <p>
#  * The following features are supported:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.Time#getInterval <em>Interval</em>}</li>
#  *   <li>{@link org.lflang.lf.Time#getUnit <em>Unit</em>}</li>
#  * </ul>
#  *
#  * @see org.lflang.lf.LfPackage#getTime()
#  * @model
#  * @generated
#  
class Time(Expression):
    """ generated source for interface Time """
    __metaclass__ = ABCMeta
    #    * Returns the value of the '<em><b>Interval</b></em>' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Interval</em>' attribute.
    #    * @see #setInterval(int)
    #    * @see org.lflang.lf.LfPackage#getTime_Interval()
    #    * @model
    #    * @generated
    #    
    @abstractmethod
    def getInterval(self):
        """ generated source for method getInterval """

    #    * Sets the value of the '{@link org.lflang.lf.Time#getInterval <em>Interval</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Interval</em>' attribute.
    #    * @see #getInterval()
    #    * @generated
    #    
    @abstractmethod
    def setInterval(self, value):
        """ generated source for method setInterval """

    #    * Returns the value of the '<em><b>Unit</b></em>' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Unit</em>' attribute.
    #    * @see #setUnit(String)
    #    * @see org.lflang.lf.LfPackage#getTime_Unit()
    #    * @model
    #    * @generated
    #    
    @abstractmethod
    def getUnit(self):
        """ generated source for method getUnit """

    #    * Sets the value of the '{@link org.lflang.lf.Time#getUnit <em>Unit</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Unit</em>' attribute.
    #    * @see #getUnit()
    #    * @generated
    #    
    @abstractmethod
    def setUnit(self, value):
        """ generated source for method setUnit """

#  Time
