#!/usr/bin/env python
""" generated source for module TypedVariable """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# import org.eclipse.emf.common.util.EList

# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>Typed Variable</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * <p>
#  * The following features are supported:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.TypedVariable#getAttributes <em>Attributes</em>}</li>
#  *   <li>{@link org.lflang.lf.TypedVariable#getType <em>Type</em>}</li>
#  * </ul>
#  *
#  * @see org.lflang.lf.LfPackage#getTypedVariable()
#  * @model
#  * @generated
#  
class TypedVariable(Variable):
    """ generated source for interface TypedVariable """
    __metaclass__ = ABCMeta
    #    * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
    #    * The list contents are of type {@link org.lflang.lf.Attribute}.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Attributes</em>' containment reference list.
    #    * @see org.lflang.lf.LfPackage#getTypedVariable_Attributes()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getAttributes(self):
        """ generated source for method getAttributes """

    #    * Returns the value of the '<em><b>Type</b></em>' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Type</em>' containment reference.
    #    * @see #setType(Type)
    #    * @see org.lflang.lf.LfPackage#getTypedVariable_Type()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getType(self):
        """ generated source for method getType """

    #    * Sets the value of the '{@link org.lflang.lf.TypedVariable#getType <em>Type</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Type</em>' containment reference.
    #    * @see #getType()
    #    * @generated
    #    
    @abstractmethod
    def setType(self, value):
        """ generated source for method setType """

#  TypedVariable
