#!/usr/bin/env python
""" generated source for module Visibility """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
# import java.util.Arrays
# import java.util.Collections
# import java.util.List
# import org.eclipse.emf.common.util.Enumerator
from include.overloading import overloaded
# 
#  * <!-- begin-user-doc -->
#  * A representation of the literals of the enumeration '<em><b>Visibility</b></em>',
#  * and utility methods for working with them.
#  * <!-- end-user-doc -->
#  * @see org.lflang.lf.LfPackage#getVisibility()
#  * @model
#  * @generated
#  
class Visibility:
    """ generated source for enum Visibility """
    #    * The '<em><b>NONE</b></em>' literal value.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #NONE
    #    * @model
    #    * @generated
    #    * @ordered
    #    
    NONE_VALUE = 0

    #    * The '<em><b>PRIVATE</b></em>' literal value.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #PRIVATE
    #    * @model literal="private"
    #    * @generated
    #    * @ordered
    #    
    PRIVATE_VALUE = 1

    #    * The '<em><b>PUBLIC</b></em>' literal value.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @see #PUBLIC
    #    * @model literal="public"
    #    * @generated
    #    * @ordered
    #    
    PUBLIC_VALUE = 2

    #    * An array of all the '<em><b>Visibility</b></em>' enumerators.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    VALUES_ARRAY = [None] * 

    #    * A public read-only list of all the '<em><b>Visibility</b></em>' enumerators.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY))

    #    * Returns the '<em><b>Visibility</b></em>' literal with the specified literal value.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param literal the literal.
    #    * @return the matching enumerator or <code>null</code>.
    #    * @generated
    #    
    @classmethod
    @overloaded
    def get(cls, literal):
        """ generated source for method get """
        i = 0
        while len(VALUES_ARRAY):
            result = cls.VALUES_ARRAY[i]
            if result.__str__() == literal:
                return result
            i += 1
        return None

    #    * Returns the '<em><b>Visibility</b></em>' literal with the specified name.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param name the name.
    #    * @return the matching enumerator or <code>null</code>.
    #    * @generated
    #    
    @classmethod
    def getByName(cls, name):
        """ generated source for method getByName """
        i = 0
        while len(VALUES_ARRAY):
            result = cls.VALUES_ARRAY[i]
            if result.__name__ == name:
                return result
            i += 1
        return None

    #    * Returns the '<em><b>Visibility</b></em>' literal with the specified integer value.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the integer value.
    #    * @return the matching enumerator or <code>null</code>.
    #    * @generated
    #    
    @classmethod
    @get.register(object, int)
    def get_0(cls, value):
        """ generated source for method get_0 """
        if value == cls.NONE_VALUE:
            return NONE
        elif value == cls.PRIVATE_VALUE:
            return PRIVATE
        elif value == cls.PUBLIC_VALUE:
            return PUBLIC
        return None

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    value = int()

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    name = None

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    literal = None

    #    * Only this class can construct instances.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __init__(self, value, name, literal):
        """ generated source for method __init__ """
        super(Visibility, self).__init__()
        self.value = value
        self.name = name
        self.literal = literal

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def getValue(self):
        """ generated source for method getValue """
        return self.value

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def getName(self):
        """ generated source for method getName """
        return self.name

    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def getLiteral(self):
        """ generated source for method getLiteral """
        return self.literal

    #    * Returns the literal value of the enumerator, which is its string representation.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @generated
    #    
    def __str__(self):
        """ generated source for method toString """
        return self.literal

Visibility.NONE = Visibility(0, "NONE", "NONE")

Visibility.PRIVATE = Visibility(1, "PRIVATE", "private")

Visibility.PUBLIC = Visibility(2, "PUBLIC", "public")

# Visibility
