#!/usr/bin/env python
""" generated source for module WidthTerm """
from abc import ABCMeta, abstractmethod
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.lf
## import org.eclipse.emf.ecore.EObject

# 
#  * <!-- begin-user-doc -->
#  * A representation of the model object '<em><b>Width Term</b></em>'.
#  * <!-- end-user-doc -->
#  *
#  * <p>
#  * The following features are supported:
#  * </p>
#  * <ul>
#  *   <li>{@link org.lflang.lf.WidthTerm#getWidth <em>Width</em>}</li>
#  *   <li>{@link org.lflang.lf.WidthTerm#getParameter <em>Parameter</em>}</li>
#  *   <li>{@link org.lflang.lf.WidthTerm#getPort <em>Port</em>}</li>
#  *   <li>{@link org.lflang.lf.WidthTerm#getCode <em>Code</em>}</li>
#  * </ul>
#  *
#  * @see org.lflang.lf.LfPackage#getWidthTerm()
#  * @model
#  * @generated
#  
class WidthTerm(EObject):
    """ generated source for interface WidthTerm """
    __metaclass__ = ABCMeta
    #    * Returns the value of the '<em><b>Width</b></em>' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Width</em>' attribute.
    #    * @see #setWidth(int)
    #    * @see org.lflang.lf.LfPackage#getWidthTerm_Width()
    #    * @model
    #    * @generated
    #    
    @abstractmethod
    def getWidth(self):
        """ generated source for method getWidth """

    #    * Sets the value of the '{@link org.lflang.lf.WidthTerm#getWidth <em>Width</em>}' attribute.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Width</em>' attribute.
    #    * @see #getWidth()
    #    * @generated
    #    
    @abstractmethod
    def setWidth(self, value):
        """ generated source for method setWidth """

    #    * Returns the value of the '<em><b>Parameter</b></em>' reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Parameter</em>' reference.
    #    * @see #setParameter(Parameter)
    #    * @see org.lflang.lf.LfPackage#getWidthTerm_Parameter()
    #    * @model
    #    * @generated
    #    
    @abstractmethod
    def getParameter(self):
        """ generated source for method getParameter """

    #    * Sets the value of the '{@link org.lflang.lf.WidthTerm#getParameter <em>Parameter</em>}' reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Parameter</em>' reference.
    #    * @see #getParameter()
    #    * @generated
    #    
    @abstractmethod
    def setParameter(self, value):
        """ generated source for method setParameter """

    #    * Returns the value of the '<em><b>Port</b></em>' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Port</em>' containment reference.
    #    * @see #setPort(VarRef)
    #    * @see org.lflang.lf.LfPackage#getWidthTerm_Port()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getPort(self):
        """ generated source for method getPort """

    #    * Sets the value of the '{@link org.lflang.lf.WidthTerm#getPort <em>Port</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Port</em>' containment reference.
    #    * @see #getPort()
    #    * @generated
    #    
    @abstractmethod
    def setPort(self, value):
        """ generated source for method setPort """

    #    * Returns the value of the '<em><b>Code</b></em>' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @return the value of the '<em>Code</em>' containment reference.
    #    * @see #setCode(Code)
    #    * @see org.lflang.lf.LfPackage#getWidthTerm_Code()
    #    * @model containment="true"
    #    * @generated
    #    
    @abstractmethod
    def getCode(self):
        """ generated source for method getCode """

    #    * Sets the value of the '{@link org.lflang.lf.WidthTerm#getCode <em>Code</em>}' containment reference.
    #    * <!-- begin-user-doc -->
    #    * <!-- end-user-doc -->
    #    * @param value the new value of the '<em>Code</em>' containment reference.
    #    * @see #getCode()
    #    * @generated
    #    
    @abstractmethod
    def setCode(self, value):
        """ generated source for method setCode """

#  WidthTerm
