#!/usr/bin/env python
""" generated source for module LFAntlrTokenFileProvider """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.parser.antlr
# import java.io.InputStream
# import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider

class LFAntlrTokenFileProvider(IAntlrTokenFileProvider):
    """ generated source for class LFAntlrTokenFileProvider """
    def getAntlrTokenFile(self):
        """ generated source for method getAntlrTokenFile """
        classLoader = getClass().getClassLoader()
        return classLoader.getResourceAsStream("org/lflang/parser/antlr/internal/InternalLF.tokens")
