#!/usr/bin/env python
""" generated source for module LFParser """
# 
#  * generated by Xtext 2.28.0
#  
# package: org.lflang.parser.antlr
import com.google.inject.Inject
# import org.eclipse.xtext.parser.antlr.AbstractAntlrParser
# import org.eclipse.xtext.parser.antlr.XtextTokenStream

from org.lflang.parser.antlr.internal import InternalLFParser

from org.lflang.services import LFGrammarAccess

class LFParser(AbstractAntlrParser):
    """ generated source for class LFParser """
    grammarAccess = None

    def setInitialHiddenTokens(self, tokenStream):
        """ generated source for method setInitialHiddenTokens """
        tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT")

    def createParser(self, stream):
        """ generated source for method createParser """
        return InternalLFParser(stream, self.getGrammarAccess())

    def getDefaultRuleName(self):
        """ generated source for method getDefaultRuleName """
        return "Model"

    def getGrammarAccess(self):
        """ generated source for method getGrammarAccess """
        return self.grammarAccess

    def setGrammarAccess(self, grammarAccess):
        """ generated source for method setGrammarAccess """
        self.grammarAccess = grammarAccess
